# Generated by Django 4.2.7 on 2023-11-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='overall_rating',
            field=models.IntegerField(default=1),
        ),
    ]
