# Generated by Django 4.2.7 on 2023-11-29 21:33

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_orderitem_shippingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='available_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='item_pic',
            field=models.ImageField(blank=True, storage=home.models.MyStorage(), upload_to=''),
        ),
        migrations.AddField(
            model_name='items',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='overall_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
