# Generated by Django 4.2.7 on 2023-11-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_items_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_pic',
            field=models.ImageField(blank=True, upload_to='home/item_pics'),
        ),
    ]
