# Generated by Django 4.2.7 on 2023-11-14 18:23

import SystemSphereComputers.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_items_item_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_pic',
            field=models.ImageField(blank=True, storage=SystemSphereComputers.settings.MediaStorage(), upload_to='home/item_pics'),
        ),
    ]
