# Generated by Django 4.2.7 on 2023-11-14 21:26

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_items_item_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_pic',
            field=models.ImageField(blank=True, storage=home.models.MyStorage(), upload_to=''),
        ),
    ]
