# Generated by Django 4.2.7 on 2023-12-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customer_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_retailer',
            field=models.BooleanField(default=False),
        ),
    ]
