# Generated by Django 4.2.7 on 2023-12-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customer_is_retailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_retailer',
        ),
    ]
