# Generated by Django 4.2.7 on 2023-11-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_items_item_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
