# Generated by Django 4.2.7 on 2023-11-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='available_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='items',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
